[phases.setup]
nixPkgs = ["ffmpeg", "python3"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Building...'"]

[phases.start]
cmd = ". /opt/venv/bin/activate && python main.py"
